server:
  port: 9991

spring:
  application:
    name: wind-service
  datasource:
    name: master
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.10.11:3306/hard_probe?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Iot-IG#123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j2
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  redis:
      host: 172.19.10.9
      port: 6379
      password: app_!QAZxsw2
      timeout: 1000
