server:
  port: 8081

spring:
  application:
    name: wind-service
  datasource:
    name: master
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.235.112:3306/advert?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#      pool-name: DatebookHikariCP
  data:
    mongodb:
      #uri: mongodb://test:123456@192.168.235.113:27017/test
      host: 192.168.235.113
      port: 27017
      database: test
      username: root
      password: 123456
  redis:
      host: 192.168.235.112
      port: 6379
      password: 123456
      timeout: 1s

mybatis:
  type-aliases-package: com.wind.dao.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true
wind:
  logging:
    level: debug

