server:
  port: 8082
spring:
  application:
    name: wind-route


dubbo:
  application:
    name: wind-route
    id: wind-route
  registry:
    address: zookeeper://192.168.235.111:2181
    #protocol: zookeeper
  protocol:
    name: wind-route
    port: 20880
  monitor:
    protocol: registry
  consumer:
    check: false
